
library(shiny)
options(shiny.fullstacktrace = TRUE)
# UI
ui <- fluidPage(
  includeCSS("style.css"),
  fluidPage(
    h1("shinyNewColumns", align = "center"),
    br(), br(),
    # just a button next...
    fluidRow(column(12, align = "center", mod_launchModal_ui(id = "launchModal"))),
    br(),
    h3("New column's code:"),
    h4("(generated by user inputs)"),
    verbatimTextOutput("display_expr"),
    br(),
    h3("Iris data:"),
    wellPanel(dataTableOutput("display_data"))
  )
)

# Server
server <- function(input, output) {
  out <- mod_launchModal_srv(id = "launchModal", dat = iris)
  output$display_expr <- renderPrint(out$expr())
  output$display_data <- renderDataTable(out$data())
}

shinyApp(ui = ui, server = server)
